baseURL = "https://laurobmb.github.io/"
languageCode = "en-us"
title = "Lauro Gomes"
theme = "hyde-hyde"
enableEmoji = true
enableRobotsTXT = true
enableMissingTranslationPlaceholders = true

[taxonomies]
    tag="tag"
    category="categories"
    mood="moods"

[params]
    title = "Conhecimento"
    date = "2020-12-10"
    authorimage = "/about/lauro.jpeg"
    description = "Automação é vida"
    email = "lauro@laurodepaula.com.br"
    keywords = "cyber,security,devops"
    copyright = "Lauro de Paula Gomes"
    cfpUrl = "https://laurobmb.wordpress.com"
    subscriptionUrl = "https://laurobmb.wordpress.com"
    appleTouchIcon = "/apple-touch-icon.png"
    favicon32 = "/favicon-32x32.png"
    favicon16 = "/favicon-16x16.png"
    manifest = "/manifest.json"
    safariPinnedTab = "/safari-pinned-tab.svg"
    themeColor = "#673ab7"
    mainSections = ["posts","sobre"]
    highlightjs = true
    highlightjsstyle = "github"

[params.logos]
    jumbo = "/images/logos/devfest_color_text.png"
    header = "/images/logos/devfest_color_text.png"
    footer = "/images/logos/devfest_gray_text.png"

[params.social]
    twitter = "laurobmb"
    github = "laurobmb"
    gitlab = "laurobmb"
    linkedin = "laurodepaula"
    telegram = "laurobmb"
    gravatar = "laurobmb@gmail.com"

[menu]

    [[menu.main]]
        title = "sobre"
        name = "sobre"
        identifier = "sobre"
        weight = 20
        url = "/about/"

    [[menu.main]]
        title = "posts"
        name = "posts"
        identifier = "posts"
        weight = 30
        url = "/posts/"

    [[menu.main]]
        title = "projetos"
        name = "projetos"
        identifier = "projetos"
        weight = 30
        url = "/projetos/"
